# Generated by Django 4.1.7 on 2023-03-12 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pumpkin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('reference', models.CharField(max_length=60)),
                ('etat', models.CharField(choices=[(1, 'Neuf'), (2, 'Bon'), (3, 'Moyen'), (4, 'Acceptable'), (5, 'Mauvais'), (6, 'Très mauvais')], max_length=20)),
                ('commentaire', models.TextField()),
                ('date_achat', models.DateField(verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
