# Generated by Django 4.1.7 on 2023-03-12 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpkin', '0002_item_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_achat',
            field=models.DateField(verbose_name=datetime.datetime(2023, 3, 12, 15, 13, 23, 984442, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='etat',
            field=models.CharField(choices=[(1, 'Neuf'), (2, 'Bon'), (3, 'Moyen'), (4, 'Acceptable'), (5, 'Mauvais'), (6, 'Très mauvais')], default=1, max_length=25),
        ),
    ]
