# Generated by Django 4.1.7 on 2023-03-12 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpkin', '0003_alter_item_date_achat_alter_item_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_achat',
            field=models.DateField(verbose_name=datetime.datetime(2023, 3, 12, 15, 16, 37, 432509, tzinfo=datetime.timezone.utc)),
        ),
    ]
