# Generated by Django 4.1.7 on 2023-03-12 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpkin', '0004_alter_item_date_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_achat',
            field=models.DateField(verbose_name=datetime.datetime(2023, 3, 12, 16, 20, 0, 631922)),
        ),
    ]
