# Generated by Django 4.1.7 on 2023-03-12 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpkin', '0006_alter_item_date_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_achat',
            field=models.DateField(default=datetime.date(2023, 3, 12)),
        ),
    ]
