# Generated by Django 4.1.7 on 2023-03-12 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pumpkin', '0007_alter_item_date_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_achat',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
