# Generated by Django 4.1.7 on 2023-03-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpkin', '0009_item_creation_date_item_quantite_item_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creation_date',
            field=models.DateField(default='2023-03-13'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_achat',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='etat',
            field=models.CharField(choices=[(1, 'Neuf'), (2, 'Bon'), (3, 'Moyen'), (4, 'Acceptable'), (5, 'Mauvais'), (6, 'Très Mauvais')], default=1, max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_date',
            field=models.DateField(default='2023-03-13'),
        ),
    ]
