# Generated by Django 4.1.7 on 2023-03-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpkin', '0012_alter_item_date_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='etat',
            field=models.IntegerField(choices=[(1, 'Neuf'), (2, 'Bon'), (3, 'Moyen'), (4, 'Acceptable'), (5, 'Mauvais'), (6, 'Très Mauvais')], default=1, max_length=25),
        ),
    ]
