# Generated by Django 4.1.7 on 2023-03-13 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpkin', '0014_alter_item_date_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantite',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
